[".config/zsh/.zprezto"]
    type = "git-repo"
    url = "https://github.com/sorin-ionescu/prezto.git"
    refreshPeriod = "168h"
    [".config/zsh/.zprezto".clone]
        args = ["--recurse-submodules"]
    [".config/zsh/.zprezto".pull]
        args = ["--recurse-submodules"]

[".config/nvim"]
    type = "git-repo"
    url = "https://github.com/NvChad/NvChad"
    refreshPeriod = "168h"
 
