[".config/zsh/.zprezto"]
    type = "git-repo"
    url = "https://github.com/sorin-ionescu/prezto.git"
    refreshPeriod = "168h"
    [".config/zsh/.zprezto".clone]
        args = ["--recurse-submodules"]
    [".config/zsh/.zprezto".pull]
        args = ["--recurse-submodules"]

[".config/zsh/.zprezto/contrib"]
    type = "git-repo"
    url = "https://github.com/belak/prezto-contrib"
    refreshPeriod = "168h"
    [".config/zsh/.zprezto/contrib".clone]
        args = ["--recurse-submodules"]
    [".config/zsh/.zprezto/contrib".pull]
        args = ["--recurse-submodules"]
